bank/urls.py
from django.urls import path, include
from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('user/', views.scan_card, name='scan_card'),
    path('user/<int:card_number>/', views.user_profile, name='user_profile'),
    path('user/<int:card_number>/deposit', views.deposit_money, name='deposit'),
    path('user/<int:card_number>/withdraw', views.withdraw_money, name='withdraw'),
    path('total_money/', views.total_money, name='total_money'),
]

config/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'config'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('bank/', include('bank.urls', namespace='bank')),
    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='home.html'), name='logout'),
    path('switch/guest', views.switch_to_guest, name='switch_to_guest'),
]

yg_system/urls.py
from django.urls import path, include
from django.contrib import admin

app_name = 'yg_system'

urlpatterns = [
    path('', include('config.urls'),),
    path('admin/', admin.site.urls),
]

yg_system/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block links %}
    {% endblock %}
</head>
<body>
<a href="{% url 'config:home_page' %}">Home</a> |
<a href="{% url 'config:bank:home_page' %}">Bank</a>
<a href="{% url 'admin:index' %}">Admin</a>
<a href="{% url 'config:attendance:home_page' %}">Attendance</a>
{% if user.is_authenticated %}
    {% if user.username == 'admin' %}
        <a href="{% url 'config:switch_to_guest' %}">Switch to Guest</a>
    {% endif %}
  <a href="{% url 'config:logout' %}">Log Out</a>
{% else %}
  <a href="{% url 'config:login' %}">Log In</a>
{% endif %}
<div>
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

yg_system/templates/home.html
{% extends 'base.html' %}

{% block title %}YG Academy{% endblock %}