attendance/urls.py
from django.urls import path
from . import views

app_name = 'attendance'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('sunday_school/', views.sunday_school, name='sunday_school'),
    path('bible_study/', views.bible_study, name='bible_study'),
    path('summer_club/', views.summer_club, name='summer_club'),
    path('sunday_school/card', views.card_attendance_sunday_school, name='ss_attendance'),
    path('bible_study/card', views.card_attendance_bible_study, name='bs_attendance'),
    path('summer_club/card', views.card_attendance_summer_club, name='sc_attendance'),
    path('sunday_school/name', views.name_attendance_sunday_school, name='ss_attendance_name'),
    path('bible_study/name', views.name_attendance_bible_study, name='bs_attendance_name'),
    path('summer_club/name', views.name_attendance_summer_club, name='sc_attendance_name'),

]

bank/urls.py
from django.urls import path, include
from . import views

app_name = 'bank'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('user/', views.scan_card, name='scan_card'),
    path('user/<int:card_number>/', views.user_profile, name='user_profile'),
    path('user/<int:card_number>/deposit', views.deposit_money, name='deposit'),
    path('user/<int:card_number>/withdraw', views.withdraw_money, name='withdraw'),
    path('total_money/', views.total_money, name='total_money'),
]

yg_system/urls.py
from django.urls import path, include
from django.contrib import admin

app_name = 'yg_system'

urlpatterns = [
    path('', include('config.urls'),),
    path('admin/', admin.site.urls),
]

attendance/models/attendance.py
from django.db import models
from config.models.student import Student
from .day import Day


class Attendance(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='attendance')
    day = models.ForeignKey(Day, on_delete=models.CASCADE, related_name='attendance')
    by_card = models.BooleanField(default=True)

    class Meta:
        unique_together = ('student', 'day')

    def __str__(self):
        return f'{self.day.get_service()} - {self.day.date}: {self.student}'

attendance/models/day.py
from django.db import models
from config.models.student import Student


class Day(models.Model):
    date = models.DateField()
    for_sunday_school = models.BooleanField(default=True)
    for_bible_study = models.BooleanField(default=False)
    attendees = models.ManyToManyField(Student, through='Attendance')

    class Meta:
        unique_together = ('date', 'for_sunday_school', 'for_bible_study')

    def get_service(self) -> str:
        if self.for_sunday_school:
            return 'Sunday School'
        elif self.for_bible_study:
            return 'Bible Study'
        return 'Summer Club'

    def __str__(self):
        return str(self.date)

attendance/models/multiplier.py
from django.db import models
from config.models.student import Student


class Multiplier(models.Model):
    student = models.OneToOneField(Student,
                                   related_name='multiplier',
                                   on_delete=models.CASCADE)
    sunday_school = models.IntegerField(default=0)
    bible_study = models.IntegerField(default=0)
    summer_club = models.IntegerField(default=0)

attendance/models/start_year.py
from django.db import models


class StartYear(models.Model):
    year = models.DateField()

attendance/views/attendance_by_card.py
from django.shortcuts import render, redirect
from attendance.services import AttendanceService
from bank.selectors import CardSelector
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from config.selectors.student import StudentSelector
from attendance.selectors.attendance import AttendanceSelector
from django.http import HttpResponse


def card_attendance_sunday_school(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    err, card = '', ''
    card_number = request.POST['card_number']
    student_names = StudentSelector().get_all_student_names()

    try:
        card = CardSelector().get_card_by_number(card_number)
        AttendanceService().add_attendance_by_card(card=card,
                                                   for_sunday_school=True)
    except ObjectDoesNotExist:
        err = 'Card does not exist.'
    except IntegrityError:
        err = f'{str(card.holder)} has already been recorded.'

    context = {
        'err': err,
        'student_names': student_names,
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(for_sunday_school=True),
    }
    return render(request, 'attendance/sunday_school.html', context)


def card_attendance_bible_study(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    err, card = '', ''
    card_number = request.POST['card_number']
    student_names = StudentSelector().get_all_student_names()

    try:
        card = CardSelector().get_card_by_number(card_number)
        AttendanceService().add_attendance_by_card(card=card,
                                                   for_bible_study=True)
    except ObjectDoesNotExist:
        err = 'Card does not exist.'
    except IntegrityError:
        err = f'{str(card.holder)} has already been recorded.'

    context = {
        'err': err,
        'student_names': student_names,
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(for_bible_study=True),
    }
    return render(request, 'attendance/bible_study.html', context)


def card_attendance_summer_club(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    err, card = '', ''
    card_number = request.POST['card_number']
    student_names = StudentSelector().get_all_student_names()

    try:
        card = CardSelector().get_card_by_number(card_number)
        AttendanceService().add_attendance_by_card(card=card)
    except ObjectDoesNotExist:
        err = 'Card does not exist.'
    except IntegrityError:
        err = f'{str(card.holder)} has already been recorded.'

    context = {
        'err': err,
        'student_names': student_names,
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(),
    }
    return render(request, 'attendance/summer_club.html', context)

attendance/views/attendance_by_name.py
from django.shortcuts import render, redirect
from attendance.services import AttendanceService
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from config.selectors.student import StudentSelector
from attendance.selectors.attendance import AttendanceSelector
from django.http import HttpResponse


def name_attendance_sunday_school(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    err, student = '', ''
    full_name = request.POST['full_name']
    student_names = StudentSelector().get_all_student_names()

    try:
        student = StudentSelector.get_student_by_full_name(full_name)
        AttendanceService().add_attendance_by_student(student, for_sunday_school=True)
    except ObjectDoesNotExist:
        err = 'Name does not exist.'
    except IntegrityError:
        err = f'{str(student)} has already been recorded.'

    context = {
        'err': err,
        'student_names': student_names,
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(for_sunday_school=True),
    }
    return render(request, 'attendance/sunday_school.html', context)


def name_attendance_bible_study(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    err, student = '', ''
    full_name = request.POST['full_name']
    student_names = StudentSelector().get_all_student_names()

    try:
        student = StudentSelector.get_student_by_full_name(full_name)
        AttendanceService().add_attendance_by_student(student, for_bible_study=True)
    except ObjectDoesNotExist:
        err = 'Name does not exist.'
    except IntegrityError:
        err = f'{str(student)} has already been recorded.'

    context = {
        'err': err,
        'student_names': student_names,
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(for_bible_study=True),
    }
    return render(request, 'attendance/bible_study.html', context)


def name_attendance_summer_club(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    err, student = '', ''
    full_name = request.POST['full_name']
    student_names = StudentSelector().get_all_student_names()

    try:
        student = StudentSelector.get_student_by_full_name(full_name)
        AttendanceService().add_attendance_by_student(student)
    except ObjectDoesNotExist:
        err = 'Name does not exist.'
    except IntegrityError:
        err = f'{str(student)} has already been recorded.'

    context = {
        'err': err,
        'student_names': student_names,
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(),
    }
    return render(request, 'attendance/summer_club.html', context)

attendance/views/bible_study.py
from django.shortcuts import render, redirect
from attendance.selectors.attendance import AttendanceSelector
from config.selectors.student import StudentSelector
from django.http import HttpResponse


def bible_study(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    context = {
        'title': "Bible Study",
        'student_names': StudentSelector().get_all_student_names(),
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(for_bible_study=True),
    }
    return render(request, 'attendance/bible_study.html', context)

attendance/views/home_page.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def home_page(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    return render(request, 'attendance/home.html')

attendance/views/summer_club.py
from django.shortcuts import render, redirect
from attendance.selectors.attendance import AttendanceSelector
from config.selectors.student import StudentSelector
from django.http import HttpResponse


def summer_club(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    context = {
        'title': "Summer Club",
        'student_names': StudentSelector().get_all_student_names(),
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(),
    }
    return render(request, 'attendance/summer_club.html', context)

attendance/views/sunday_school.py
from django.shortcuts import render, redirect
from attendance.selectors.attendance import AttendanceSelector
from config.selectors.student import StudentSelector
from django.http import HttpResponse


def sunday_school(request):

    if not request.user.is_authenticated:
        return redirect('config:login')
    if request.user.username != 'admin':
        return HttpResponse('Unauthorized', status=401)

    context = {
        'title': "Sunday School",
        'student_names': StudentSelector().get_all_student_names(),
        'attendance_count': AttendanceSelector.get_attendance_count_by_day(for_sunday_school=True),
    }
    return render(request, 'attendance/sunday_school.html', context)

yg_system/templates/attendance/bible_study.html
{% extends 'attendance/home.html' %}

{% block body %}
    <h1>Bible Study</h1>

    <form action="{% url 'config:attendance:bs_attendance' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the card number:</label><br>
      <input type="number" id="card_number" name="card_number" autofocus><br>
      <input type="submit" value="Submit">
    </form>

    <form action="{% url 'config:attendance:bs_attendance_name' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the student's name:</label><br>
      <input id="full_name" name="full_name" list="Full Name"><br>
        <datalist id="Full Name">
        {% for student in student_names %}
            <option value="{{ student }}">
        {% endfor %}
        </datalist>
      <input type="submit" value="Submit">
    </form>

    <p>Attendance Count: {{ attendance_count }}</p>

    {% if err %}
        <p>{{ err }}</p>
    {% endif %}
{% endblock %}

yg_system/templates/attendance/home.html
{% extends 'base.html' %}

{% block title %}Attendance{% endblock %}

{% block body %}
    Welcome to the Attendance

    <form action="{% url 'config:attendance:bible_study' %}" method="post">
      {% csrf_token %}
      <input id="id_bible_study" type="submit" value="Bible Study">
    </form>

    <form action="{% url 'config:attendance:sunday_school' %}" method="post">
      {% csrf_token %}
      <input id="id_sunday_school" type="submit" value="Sunday School">
    </form>

    <form action="{% url 'config:attendance:summer_club' %}" method="post">
      {% csrf_token %}
      <input id="id_summer_club" type="submit" value="Summer Club">
    </form>

{% endblock %}

yg_system/templates/attendance/service.html
{% extends 'attendance/home.html' %}

{% block body %}
    <h1>{{ title }}</h1>

    <form action="{% url 'config:attendance:ss_attendance' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the card number:</label><br>
      <input type="text" id="card_number" name="card_number"><br>
      <input type="submit" value="Submit">
    </form>
{% endblock %}

yg_system/templates/attendance/summer_club.html
{% extends 'attendance/home.html' %}

{% block body %}
    <h1>Summer Club</h1>

    <form action="{% url 'config:attendance:sc_attendance' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the card number:</label><br>
      <input type="number" id="card_number" name="card_number" autofocus><br>
      <input type="submit" value="Submit">
    </form>

    <form action="{% url 'config:attendance:sc_attendance_name' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the student's name:</label><br>
      <input id="full_name" name="full_name" list="Full Name"><br>
        <datalist id="Full Name">
        {% for student in student_names %}
            <option value="{{ student }}">
        {% endfor %}
        </datalist>
      <input type="submit" value="Submit">
    </form>

    <p>Attendance Count: {{ attendance_count }}</p>

    {% if err %}
        <p>{{ err }}</p>
    {% endif %}
{% endblock %}

yg_system/templates/attendance/sunday_school.html
{% extends 'attendance/home.html' %}

{% block body %}
    <h1>Sunday School</h1>

    <form action="{% url 'config:attendance:ss_attendance' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the card number:</label><br>
      <input type="number" id="card_number" name="card_number" autofocus><br>
      <input type="submit" value="Submit">
    </form>

    <form action="{% url 'config:attendance:ss_attendance_name' %}" method="post">
      {% csrf_token %}
      <label for="card_number">Please enter the student's name:</label><br>
      <input id="full_name" name="full_name" list="Full Name"><br>
        <datalist id="Full Name">
        {% for student in student_names %}
            <option value="{{ student }}">
        {% endfor %}
        </datalist>
      <input type="submit" value="Submit">
    </form>

    <p>Attendance Count: {{ attendance_count }}</p>

    {% if err %}
        <p>{{ err }}</p>
    {% endif %}
{% endblock %}